id: A4A27C44B
base_file: f66EF.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:07:51.379032
  last_modified_at: 2022-05-30 23:07:51.379040
